### ISSUE TITLE
How do i connect to different virtual servers

### ISSUE THREAD

**Issue by dceonline** [Kissaki/MumPI#64]
Hi,

just installed mumble-server and mumpi and setup a second server under the same IP and same port. If i connect to server using IP and port with a new username, i always hit the first (virtual) server. So how can i manage to connect to the second server without registered user?

Regards

Ortwin

**Comment by Kissaki** [comment]
You can not host two servers on the same port. The port is what allows networking to identify the program destination. You will have to assign a different port for your second virtual server.

**Comment by dceonline** [comment]
Misunderstood! I am just working with only one real server (murmur) and want to use it with some virtual servers. So if i use virtual servers, have i also to choose a different port for each virtual server and config it in mumpi? Or is there a way to address differnt virtual servers on murmur using the same port? I checked out the mumble wiki but there wasn' t an answer for that.

**Comment by Kissaki** [comment]
Creating a new virtual server in MumPI will automatically set the port to the previous port + 1, giving it a new port. So by default, it works with that different port without additional configuration.

Launching the Mumble server launches one system process. That process may contain multiple virtual servers, of which each one has its own port - because the port defines the destination virtual server. If you had one port for two virtual servers, when it receives a voice packet it would not know which virtual server to send it to.

**Comment by dceonline** [comment]
Thx Jan, that' s what i needed to know. :)

Regards

Ortwin
